coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
    patch:
      default:
        target: 100%
        threshold: 0%

ignore:
  - "test/**/*"
  - "docs/**/*"
  - ".github/**/*"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: yes
  require_head: yes

